# Generated by Django 2.0.2 on 2018-05-20 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trunk', models.IntegerField()),
                ('port', models.CharField(max_length=20)),
                ('sgNum', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('portal', models.CharField(max_length=10)),
                ('das', models.IntegerField(unique=True)),
                ('dpc', models.CharField(max_length=11, unique=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('circuits', models.ManyToManyField(to='indexPage.Circuit')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MgcfCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MgwCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, unique=True)),
                ('physical_num', models.CharField(max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SssCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('code', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='mgcf_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='indexPage.MgcfCode'),
        ),
        migrations.AddField(
            model_name='company',
            name='mgw_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='indexPage.MgwCode'),
        ),
        migrations.AddField(
            model_name='company',
            name='numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='indexPage.Number'),
        ),
        migrations.AddField(
            model_name='company',
            name='sss_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='indexPage.SssCode'),
        ),
    ]
