# Generated by Django 2.0.2 on 2018-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creatDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
